GET http://localhost:3000/posts

###
GET http://localhost:3000/posts/5f0f0ed467ae6329a0cd680e

###

POST http://localhost:3000/posts 
content-type: application/json

{
    "title" :  "First post",
    "description" : "This is my Description of awesome lovelife"
}   

###

POST http://localhost:3000/posts 
content-type: application/json

{
    "title" :  "second post",
    "description" : "This is my awesome Description"
}   


###
DELETE  http://localhost:3000/posts/5f0f13304618ea2ddcfcb327


###
PATCH http://localhost:3000/posts/5f0f13774618ea2ddcfcb329
content-type: application/json

{
    "title" :  "third post",
    "description" : "This is my awesome Description"
}   

###

GET https://intense-dusk-11133.herokuapp.com/posts
